services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: piwren
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'
